// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityEventManagement.Infrastructure.Data;

#nullable disable

namespace UniversityEventManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525125003_AddEfCorePersistence")]
    partial class AddEfCorePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 60,
                            Category = "Workshop",
                            Description = "Hands-on workshop covering the fundamentals of machine learning using Python and scikit-learn.",
                            EndDate = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartDate = new DateTime(2026, 4, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "AI & Machine Learning Workshop",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 300,
                            Category = "Cultural",
                            Description = "An evening celebrating the diverse cultures of IUS students.",
                            EndDate = new DateTime(2026, 4, 20, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartDate = new DateTime(2026, 4, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "IUS Spring Cultural Night",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            Category = "Seminar",
                            Description = "Learn how to structure, write and publish academic research papers.",
                            EndDate = new DateTime(2026, 4, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartDate = new DateTime(2026, 4, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Upcoming",
                            Title = "Research Paper Writing Seminar",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 500,
                            Category = "Academic",
                            Description = "Meet representatives from companies and bring your CV.",
                            EndDate = new DateTime(2026, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartDate = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Past",
                            Title = "Career Fair 2026",
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("bit");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckedIn = false,
                            EventId = 1,
                            RegisteredAt = new DateTime(2026, 4, 1, 10, 22, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckedIn = false,
                            EventId = 2,
                            RegisteredAt = new DateTime(2026, 4, 2, 8, 14, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CheckedIn = true,
                            EventId = 1,
                            RegisteredAt = new DateTime(2026, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "student@ius.edu.ba",
                            JoinedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Student",
                            Role = "Student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Email = "organizer@ius.edu.ba",
                            JoinedAt = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Organizer",
                            Role = "Organizer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin@ius.edu.ba",
                            JoinedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin User",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lejla@ius.edu.ba",
                            JoinedAt = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lejla Muratovic",
                            Role = "Student",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 300,
                            Location = "Building A, Floor 1",
                            Name = "Main Auditorium"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Location = "Building B, Floor 1",
                            Name = "Seminar Room 101"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 60,
                            Location = "Building C, Floor 2",
                            Name = "Computer Lab 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 500,
                            Location = "Campus Center",
                            Name = "Open Courtyard"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 120,
                            Location = "Building A, Floor 3",
                            Name = "Conference Hall"
                        });
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Event", b =>
                {
                    b.HasOne("UniversityEventManagement.Domain.Entities.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityEventManagement.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Registration", b =>
                {
                    b.HasOne("UniversityEventManagement.Domain.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityEventManagement.Domain.Entities.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("OrganizedEvents");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("UniversityEventManagement.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
